server:
  port: 8080
spring:
  main:
    allow-circular-references: true

block:
  # 设定哈希值前difficulty位都是0时,满足计算结果
  difficulty: 4
  # 当前节点 websocket server端口号
  port: 7002
  # 要连接的节点地址
  address: ws://192.168.1.4:7001